### ISSUE TITLE
Encounter problems when try to convert IFC to Wexbim

### ISSUE THREAD

**Issue by zhengcongyin** [xBimTeam/XbimUtilities#1]
Hello developers,
I tried to use XbimUtilities to convert IFC to Wexbim for geometry and data of the BIM model. I downloaded latest version of XbimUtilities, installed the needed Nuget Packages,and set XbimConvert as a start project, when click "start" button. However, the error messages pop up as the attached screenshot. The Essential and geometry packages are installed. And I also added "Xbim-Master" as package source. Could you tell me how to fix the problem or the way to use Xbim exchange. Thank you very much in advanced.
![image](https://cloud.githubusercontent.com/assets/10716937/10591533/3c10924c-767c-11e5-8fd9-f87bb4dff11e.png)

Best,
ZC

**Comment by CBenghi** [comment]
Hello,
whenever you encounter one of our packages that ends with a V000x version, that refers to our unstable branch "develop".
Its packages are available on Myget at the url https://www.myget.org/F/xbim-develop/api/v2 
Best,
Claudio
